project_id          = "civil-liberties-observatory"
region              = "us-central1"
bucket_name         = "civil-liberties-data"
prod_dataset_id     = "civil-liberties-prod"
staging_dataset_id  = "civil-liberties-staging"
admin_email         = "njogumwaniki9@gmail.com"