name: civil_liberties_pipeline
schedule: "@daily"
start_date: "2023-06-01"

default_connections:
  duckdb: duckdb-parquet
  google_cloud_platform: bigquery-default

variables:
  bq_dataset:
    type: string
    default: "civil_liberties_staging"

  project_id:
    type: string
    default: "encoded-joy-485413-k5"

  country:
    type: string
    default: "Kenya"

  iso2:
    type: string
    default: "KE"

  start_date:
    type: string
    default: "2023-06-01"

  end_date:
    type: string
    default: "2025-06-30"
